export interface Word {
  word: string;
  synonyms: string[];
  definition: string;
}

export const WORDS: Word[] = [
  { word: "outcry", synonyms: ["clamor", "uproar", "protest", "furor"], definition: "(n.) A loud shout or protest" },
  { word: "abridge", synonyms: ["shorten", "condense", "curtail", "truncate"], definition: "(v.) To shorten by condensing" },
  { word: "acrimony", synonyms: ["bitterness", "hostility", "rancor", "animosity"], definition: "(n.) Bitterness or ill feeling" },
  { word: "admonish", synonyms: ["warn", "reprove", "rebuke", "caution"], definition: "(v.) To warn or reprimand firmly" },
  { word: "affluent", synonyms: ["wealthy", "prosperous", "opulent", "rich"], definition: "(adj.) Having a great deal of money; wealthy" },
  { word: "aloof", synonyms: ["distant", "detached", "indifferent", "remote"], definition: "(adj.) Not friendly or forthcoming" },
  { word: "ambiguous", synonyms: ["vague", "unclear", "equivocal", "obscure"], definition: "(adj.) Open to more than one interpretation" },
  { word: "ameliorate", synonyms: ["improve", "enhance", "better", "alleviate"], definition: "(v.) To make something bad better" },
  { word: "amiable", synonyms: ["friendly", "affable", "genial", "pleasant"], definition: "(adj.) Having a friendly and pleasant manner" },
  { word: "anguish", synonyms: ["agony", "distress", "torment", "suffering"], definition: "(n.) Severe mental or physical pain" },
  { word: "antagonize", synonyms: ["provoke", "irritate", "alienate", "oppose"], definition: "(v.) To cause someone to become hostile" },
  { word: "apathy", synonyms: ["indifference", "lethargy", "listlessness", "detachment"], definition: "(n.) Lack of interest or enthusiasm" },
  { word: "appease", synonyms: ["pacify", "placate", "mollify", "soothe"], definition: "(v.) To pacify or satisfy a demand" },
  { word: "arid", synonyms: ["dry", "barren", "parched", "sterile"], definition: "(adj.) Having little or no rain; too dry" },
  { word: "articulate", synonyms: ["eloquent", "fluent", "expressive", "coherent"], definition: "(adj.) Having or showing the ability to speak clearly" },
  { word: "astute", synonyms: ["shrewd", "clever", "perceptive", "sharp"], definition: "(adj.) Having an ability to accurately assess situations" },
  { word: "audacious", synonyms: ["bold", "daring", "brazen", "intrepid"], definition: "(adj.) Showing willingness to take bold risks" },
  { word: "austere", synonyms: ["severe", "stern", "spartan", "ascetic"], definition: "(adj.) Severe or strict in manner; simple and plain" },
  { word: "banal", synonyms: ["trite", "mundane", "clichéd", "hackneyed"], definition: "(adj.) So lacking in originality as to be boring" },
  { word: "belligerent", synonyms: ["aggressive", "hostile", "combative", "pugnacious"], definition: "(adj.) Hostile and aggressive" },
  { word: "benevolent", synonyms: ["kind", "charitable", "generous", "philanthropic"], definition: "(adj.) Well meaning and kindly" },
  { word: "bolster", synonyms: ["reinforce", "support", "strengthen", "shore up"], definition: "(v.) To support or strengthen" },
  { word: "brevity", synonyms: ["conciseness", "terseness", "succinctness", "pithiness"], definition: "(n.) Concise and exact use of words" },
  { word: "callous", synonyms: ["insensitive", "heartless", "cold", "unfeeling"], definition: "(adj.) Showing or having an insensitive disregard for others" },
  { word: "candid", synonyms: ["frank", "honest", "forthright", "sincere"], definition: "(adj.) Truthful and straightforward" },
  { word: "capricious", synonyms: ["unpredictable", "whimsical", "erratic", "impulsive"], definition: "(adj.) Given to sudden and unaccountable changes of mood" },
  { word: "censure", synonyms: ["condemn", "criticize", "reprimand", "rebuke"], definition: "(v.) To express severe disapproval of" },
  { word: "charisma", synonyms: ["charm", "magnetism", "appeal", "allure"], definition: "(n.) Compelling attractiveness or charm" },
  { word: "circumspect", synonyms: ["cautious", "prudent", "wary", "careful"], definition: "(adj.) Wary and unwilling to take risks" },
  { word: "clamor", synonyms: ["uproar", "outcry", "commotion", "din"], definition: "(n.) A loud and confused noise" },
  { word: "coerce", synonyms: ["force", "compel", "pressure", "intimidate"], definition: "(v.) To persuade by using force or threats" },
  { word: "compel", synonyms: ["force", "oblige", "coerce", "drive"], definition: "(v.) To force or strongly pressure" },
  { word: "complacent", synonyms: ["smug", "self-satisfied", "content", "unconcerned"], definition: "(adj.) Showing smugness or excessive self-satisfaction" },
  { word: "conciliate", synonyms: ["pacify", "appease", "placate", "mediate"], definition: "(v.) To stop someone feeling angry; to make peace" },
  { word: "condone", synonyms: ["overlook", "excuse", "pardon", "forgive"], definition: "(v.) To accept and allow behavior considered wrong" },
  { word: "confound", synonyms: ["confuse", "bewilder", "puzzle", "baffle"], definition: "(v.) To cause surprise or confusion" },
  { word: "conscientious", synonyms: ["diligent", "meticulous", "thorough", "scrupulous"], definition: "(adj.) Wishing to do what is right; careful and precise" },
  { word: "contentious", synonyms: ["controversial", "disputed", "debatable", "divisive"], definition: "(adj.) Causing or likely to cause argument" },
  { word: "corroborate", synonyms: ["confirm", "verify", "validate", "substantiate"], definition: "(v.) To confirm or support with evidence" },
  { word: "covet", synonyms: ["desire", "crave", "envy", "yearn for"], definition: "(v.) To yearn to possess something belonging to another" },
  { word: "cryptic", synonyms: ["mysterious", "enigmatic", "puzzling", "obscure"], definition: "(adj.) Having a hidden or ambiguous meaning" },
  { word: "curtail", synonyms: ["reduce", "limit", "restrict", "cut back"], definition: "(v.) To reduce in extent or quantity" },
  { word: "debacle", synonyms: ["disaster", "fiasco", "catastrophe", "collapse"], definition: "(n.) A sudden and utter failure" },
  { word: "deceitful", synonyms: ["dishonest", "deceptive", "fraudulent", "duplicitous"], definition: "(adj.) Guilty of or involving deceit; misleading" },
  { word: "defer", synonyms: ["delay", "postpone", "yield", "submit"], definition: "(v.) To put off to a later time; to yield to another's wishes" },
  { word: "degrade", synonyms: ["demean", "humiliate", "belittle", "dishonor"], definition: "(v.) To treat or regard with contempt; lower in status" },
  { word: "deliberate", synonyms: ["intentional", "calculated", "planned", "conscious"], definition: "(adj.) Done consciously and intentionally" },
  { word: "denounce", synonyms: ["condemn", "criticize", "censure", "decry"], definition: "(v.) To publicly declare to be wrong or evil" },
  { word: "depict", synonyms: ["portray", "represent", "illustrate", "show"], definition: "(v.) To represent by a drawing, painting, or words" },
  { word: "deplete", synonyms: ["exhaust", "drain", "use up", "empty"], definition: "(v.) To use up the supply of" },
  { word: "desolate", synonyms: ["bleak", "barren", "deserted", "dreary"], definition: "(adj.) Feeling or showing great unhappiness; deserted" },
  { word: "despondent", synonyms: ["dejected", "downhearted", "melancholy", "hopeless"], definition: "(adj.) In low spirits from loss of hope or courage" },
  { word: "detrimental", synonyms: ["harmful", "damaging", "injurious", "adverse"], definition: "(adj.) Tending to cause harm" },
  { word: "dignified", synonyms: ["stately", "noble", "distinguished", "composed"], definition: "(adj.) Having or showing a composed, serious manner" },
  { word: "diligent", synonyms: ["hardworking", "industrious", "conscientious", "assiduous"], definition: "(adj.) Having or showing care and effort in work" },
  { word: "diminish", synonyms: ["reduce", "lessen", "decrease", "dwindle"], definition: "(v.) To make or become less" },
  { word: "discern", synonyms: ["perceive", "detect", "recognize", "distinguish"], definition: "(v.) To recognize or find out; to see clearly" },
  { word: "disdain", synonyms: ["contempt", "scorn", "derision", "disrespect"], definition: "(n.) The feeling that something is unworthy of consideration" },
  { word: "dismay", synonyms: ["alarm", "distress", "appall", "unsettle"], definition: "(v.) To cause someone to feel concern or distress" },
  { word: "disparage", synonyms: ["belittle", "denigrate", "deprecate", "mock"], definition: "(v.) To regard or represent as being of little worth" },
  { word: "docile", synonyms: ["obedient", "compliant", "submissive", "manageable"], definition: "(adj.) Ready to accept control; easy to manage" },
  { word: "dubious", synonyms: ["doubtful", "questionable", "uncertain", "suspicious"], definition: "(adj.) Hesitating or doubting; not to be relied upon" },
  { word: "dwindle", synonyms: ["diminish", "decrease", "shrink", "decline"], definition: "(v.) To diminish gradually in size, amount, or strength" },
  { word: "eccentric", synonyms: ["quirky", "unconventional", "odd", "peculiar"], definition: "(adj.) Unconventional and slightly strange" },
  { word: "egregious", synonyms: ["outrageous", "appalling", "atrocious", "flagrant"], definition: "(adj.) Outstandingly bad; shocking" },
  { word: "elaborate", synonyms: ["detailed", "complex", "intricate", "ornate"], definition: "(adj.) Involving many carefully arranged parts; detailed" },
  { word: "elusive", synonyms: ["evasive", "slippery", "intangible", "fleeting"], definition: "(adj.) Difficult to find, catch, or achieve" },
  { word: "eminent", synonyms: ["renowned", "distinguished", "prominent", "celebrated"], definition: "(adj.) Famous and respected within a particular sphere" },
  { word: "empathy", synonyms: ["compassion", "sympathy", "understanding", "sensitivity"], definition: "(n.) The ability to understand and share the feelings of another" },
  { word: "enervate", synonyms: ["weaken", "exhaust", "debilitate", "sap"], definition: "(v.) To make someone feel drained of energy" },
  { word: "enigmatic", synonyms: ["mysterious", "puzzling", "cryptic", "perplexing"], definition: "(adj.) Difficult to interpret or understand; mysterious" },
  { word: "erratic", synonyms: ["unpredictable", "inconsistent", "irregular", "volatile"], definition: "(adj.) Not even or regular; unpredictable" },
  { word: "evasive", synonyms: ["elusive", "equivocal", "indirect", "vague"], definition: "(adj.) Tending to avoid commitment; not straightforward" },
  { word: "exacerbate", synonyms: ["worsen", "aggravate", "intensify", "inflame"], definition: "(v.) To make a problem worse" },
  { word: "exasperate", synonyms: ["irritate", "frustrate", "annoy", "infuriate"], definition: "(v.) To irritate intensely" },
  { word: "exemplary", synonyms: ["outstanding", "admirable", "commendable", "ideal"], definition: "(adj.) Serving as a desirable model; representing the best" },
  { word: "exhaustive", synonyms: ["thorough", "comprehensive", "complete", "extensive"], definition: "(adj.) Examining every element; very thorough" },
  { word: "explicit", synonyms: ["clear", "definite", "express", "unambiguous"], definition: "(adj.) Stated clearly and in detail; leaving no room for confusion" },
  { word: "fabricate", synonyms: ["invent", "concoct", "devise", "falsify"], definition: "(v.) To invent in order to deceive" },
  { word: "fallacy", synonyms: ["misconception", "delusion", "error", "myth"], definition: "(n.) A mistaken belief based on unsound reasoning" },
  { word: "fastidious", synonyms: ["meticulous", "particular", "fussy", "scrupulous"], definition: "(adj.) Very attentive to detail; very concerned about accuracy" },
  { word: "fervent", synonyms: ["passionate", "ardent", "zealous", "intense"], definition: "(adj.) Having or displaying passionate intensity" },
  { word: "flagrant", synonyms: ["blatant", "obvious", "glaring", "egregious"], definition: "(adj.) Conspicuously or obviously offensive" },
  { word: "flippant", synonyms: ["frivolous", "glib", "dismissive", "facetious"], definition: "(adj.) Not showing a serious or respectful attitude" },
  { word: "flourish", synonyms: ["thrive", "prosper", "bloom", "succeed"], definition: "(v.) To grow or develop in a healthy way" },
  { word: "formidable", synonyms: ["daunting", "imposing", "intimidating", "awesome"], definition: "(adj.) Inspiring fear or respect through being impressively large" },
  { word: "forthright", synonyms: ["direct", "frank", "candid", "outspoken"], definition: "(adj.) Direct and outspoken; straightforward and honest" },
  { word: "frugal", synonyms: ["thrifty", "economical", "sparing", "provident"], definition: "(adj.) Sparing or economical with regard to money" },
  { word: "futile", synonyms: ["pointless", "useless", "fruitless", "vain"], definition: "(adj.) Incapable of producing any useful result; pointless" },
  { word: "garrulous", synonyms: ["talkative", "chatty", "verbose", "loquacious"], definition: "(adj.) Excessively talkative, especially on trivial matters" },
  { word: "genuine", synonyms: ["authentic", "real", "sincere", "honest"], definition: "(adj.) Truly what something is said to be; authentic" },
  { word: "grandiose", synonyms: ["ambitious", "extravagant", "pompous", "flamboyant"], definition: "(adj.) Impressively large or elaborate" },
  { word: "gratuitous", synonyms: ["unnecessary", "unwarranted", "unjustified", "uncalled for"], definition: "(adj.) Done without good reason; uncalled for" },
  { word: "gregarious", synonyms: ["sociable", "outgoing", "convivial", "friendly"], definition: "(adj.) Fond of company; sociable" },
  { word: "guile", synonyms: ["cunning", "deceit", "craftiness", "trickery"], definition: "(n.) Sly or cunning intelligence" },
  { word: "hamper", synonyms: ["hinder", "obstruct", "impede", "restrict"], definition: "(v.) To hinder or impede the movement or progress of" },
  { word: "haughty", synonyms: ["arrogant", "proud", "conceited", "pompous"], definition: "(adj.) Arrogantly superior and disdainful" },
  { word: "havoc", synonyms: ["chaos", "mayhem", "disorder", "devastation"], definition: "(n.) Widespread destruction; great confusion and disorder" },
  { word: "heresy", synonyms: ["dissent", "heterodoxy", "nonconformity", "apostasy"], definition: "(n.) Belief or opinion contrary to orthodox doctrine" },
  { word: "hypocrite", synonyms: ["fraud", "phony", "deceiver", "pretender"], definition: "(n.) A person who claims to have virtues they lack" },
  { word: "impede", synonyms: ["hinder", "obstruct", "hamper", "block"], definition: "(v.) To delay or prevent by obstructing" },
  { word: "impetuous", synonyms: ["rash", "impulsive", "hasty", "reckless"], definition: "(adj.) Acting or done quickly without thought or care" },
  { word: "incite", synonyms: ["provoke", "stimulate", "stir up", "instigate"], definition: "(v.) To encourage or stir up violent behavior" },
  { word: "indifferent", synonyms: ["apathetic", "unconcerned", "detached", "aloof"], definition: "(adj.) Having no particular interest or sympathy" },
  { word: "indulge", synonyms: ["gratify", "humor", "satisfy", "pamper"], definition: "(v.) To allow oneself to enjoy the pleasure of" },
  { word: "inevitable", synonyms: ["unavoidable", "certain", "inescapable", "definite"], definition: "(adj.) Certain to happen; unavoidable" },
  { word: "inquisitive", synonyms: ["curious", "inquiring", "nosy", "prying"], definition: "(adj.) Having or showing an interest in learning things" },
  { word: "integrity", synonyms: ["honesty", "honor", "virtue", "uprightness"], definition: "(n.) The quality of being honest and having strong moral principles" },
  { word: "intimidate", synonyms: ["frighten", "threaten", "bully", "cow"], definition: "(v.) To frighten or overawe someone" },
  { word: "jeopardize", synonyms: ["endanger", "risk", "threaten", "imperil"], definition: "(v.) To put someone or something into a situation of danger" },
  { word: "judicious", synonyms: ["wise", "prudent", "sensible", "sound"], definition: "(adj.) Having or showing good judgment" },
  { word: "lament", synonyms: ["mourn", "grieve", "bewail", "deplore"], definition: "(v.) To express sorrow, regret, or unhappiness about" },
  { word: "lethargic", synonyms: ["sluggish", "drowsy", "listless", "languid"], definition: "(adj.) Affected by lethargy; sluggish and apathetic" },
  { word: "lucid", synonyms: ["clear", "coherent", "intelligible", "transparent"], definition: "(adj.) Expressed clearly; easy to understand" },
  { word: "luminous", synonyms: ["bright", "radiant", "glowing", "brilliant"], definition: "(adj.) Full of or shedding light; bright or shining" },
  { word: "malevolent", synonyms: ["malicious", "hostile", "evil", "spiteful"], definition: "(adj.) Having or showing a wish to do evil to others" },
  { word: "meticulous", synonyms: ["careful", "precise", "thorough", "exact"], definition: "(adj.) Showing great attention to detail; very careful" },
  { word: "mitigate", synonyms: ["alleviate", "reduce", "lessen", "moderate"], definition: "(v.) To make less severe, serious, or painful" },
  { word: "mundane", synonyms: ["ordinary", "banal", "commonplace", "routine"], definition: "(adj.) Lacking interest or excitement; dull" },
  { word: "nonchalant", synonyms: ["casual", "unconcerned", "indifferent", "cool"], definition: "(adj.) Feeling or appearing casually calm and relaxed" },
  { word: "notorious", synonyms: ["infamous", "disreputable", "scandalous", "ill-famed"], definition: "(adj.) Famous for some bad quality or deed" },
  { word: "nullify", synonyms: ["invalidate", "cancel", "annul", "void"], definition: "(v.) To make legally null and void; invalidate" },
  { word: "oblivious", synonyms: ["unaware", "ignorant", "unconscious", "heedless"], definition: "(adj.) Not aware of what is happening around one" },
  { word: "obstinate", synonyms: ["stubborn", "inflexible", "tenacious", "headstrong"], definition: "(adj.) Stubbornly refusing to change one's opinion" },
  { word: "ominous", synonyms: ["threatening", "foreboding", "sinister", "menacing"], definition: "(adj.) Giving the impression that something bad will happen" },
  { word: "opulent", synonyms: ["luxurious", "lavish", "wealthy", "sumptuous"], definition: "(adj.) Ostentatiously rich and luxurious" },
  { word: "ostracize", synonyms: ["exclude", "shun", "exile", "banish"], definition: "(v.) To exclude from a society or group" },
  { word: "pacify", synonyms: ["calm", "soothe", "appease", "placate"], definition: "(v.) To bring peace to or quell the anger of" },
  { word: "paramount", synonyms: ["supreme", "preeminent", "chief", "foremost"], definition: "(adj.) More important than anything else; supreme" },
  { word: "partisan", synonyms: ["biased", "prejudiced", "one-sided", "factional"], definition: "(adj.) Prejudiced in favor of a particular cause" },
  { word: "penitent", synonyms: ["remorseful", "contrite", "repentant", "apologetic"], definition: "(adj.) Feeling or showing sorrow for wrongdoing" },
  { word: "perplexing", synonyms: ["puzzling", "baffling", "confusing", "bewildering"], definition: "(adj.) Completely baffling; very puzzling" },
  { word: "persevere", synonyms: ["persist", "continue", "endure", "press on"], definition: "(v.) To continue in a course of action despite difficulty" },
  { word: "pertinent", synonyms: ["relevant", "applicable", "appropriate", "fitting"], definition: "(adj.) Relevant or applicable to a particular matter" },
  { word: "placid", synonyms: ["calm", "tranquil", "serene", "peaceful"], definition: "(adj.) Not easily upset or excited; calm" },
  { word: "plausible", synonyms: ["believable", "credible", "reasonable", "convincing"], definition: "(adj.) Seeming reasonable or probable" },
  { word: "pompous", synonyms: ["arrogant", "self-important", "pretentious", "haughty"], definition: "(adj.) Affectedly and irritatingly grand, solemn, or self-important" },
  { word: "pragmatic", synonyms: ["practical", "realistic", "sensible", "rational"], definition: "(adj.) Dealing with things sensibly and realistically" },
  { word: "precarious", synonyms: ["unstable", "uncertain", "risky", "insecure"], definition: "(adj.) Not securely held; dangerously likely to fall" },
  { word: "pretentious", synonyms: ["pompous", "affected", "ostentatious", "showy"], definition: "(adj.) Attempting to impress by affecting greater importance" },
  { word: "proficient", synonyms: ["skilled", "expert", "adept", "competent"], definition: "(adj.) Competent or skilled in doing something" },
  { word: "prolific", synonyms: ["productive", "fertile", "fruitful", "abundant"], definition: "(adj.) Present in large numbers or producing much" },
  { word: "provocative", synonyms: ["controversial", "inflammatory", "incendiary", "challenging"], definition: "(adj.) Causing anger or another strong reaction" },
  { word: "prudent", synonyms: ["wise", "judicious", "sensible", "careful"], definition: "(adj.) Acting with or showing care and thought for the future" },
  { word: "rampant", synonyms: ["uncontrolled", "widespread", "unchecked", "rife"], definition: "(adj.) Flourishing or spreading unchecked" },
  { word: "rancor", synonyms: ["bitterness", "resentment", "spite", "animosity"], definition: "(n.) Bitterness or resentfulness" },
  { word: "reckless", synonyms: ["careless", "rash", "impetuous", "heedless"], definition: "(adj.) Without thinking about the consequences" },
  { word: "refute", synonyms: ["disprove", "rebut", "counter", "contradict"], definition: "(v.) To prove that a statement is wrong or false" },
  { word: "relentless", synonyms: ["persistent", "unremitting", "tireless", "unceasing"], definition: "(adj.) Unceasingly intense; not letting up" },
  { word: "reluctant", synonyms: ["unwilling", "hesitant", "disinclined", "loath"], definition: "(adj.) Unwilling and hesitant" },
  { word: "remorse", synonyms: ["guilt", "regret", "contrition", "penitence"], definition: "(n.) Deep regret or guilt for a wrong committed" },
  { word: "renovate", synonyms: ["restore", "refurbish", "revamp", "update"], definition: "(v.) To restore to good condition" },
  { word: "repudiate", synonyms: ["reject", "deny", "renounce", "disown"], definition: "(v.) To refuse to accept or be associated with" },
  { word: "resilient", synonyms: ["adaptable", "tough", "robust", "buoyant"], definition: "(adj.) Able to withstand or recover quickly from difficult conditions" },
  { word: "resolute", synonyms: ["determined", "steadfast", "firm", "unwavering"], definition: "(adj.) Admirably purposeful, determined, and unwavering" },
  { word: "reverence", synonyms: ["respect", "veneration", "awe", "esteem"], definition: "(n.) Deep respect for someone or something" },
  { word: "rigorous", synonyms: ["strict", "thorough", "meticulous", "demanding"], definition: "(adj.) Extremely thorough and careful" },
  { word: "ruthless", synonyms: ["merciless", "pitiless", "heartless", "cruel"], definition: "(adj.) Having or showing no pity or compassion for others" },
  { word: "sagacious", synonyms: ["wise", "shrewd", "astute", "perspicacious"], definition: "(adj.) Having or showing keen mental discernment and good judgment" },
  { word: "scrutinize", synonyms: ["examine", "inspect", "analyze", "study"], definition: "(v.) To examine or inspect closely and thoroughly" },
  { word: "serene", synonyms: ["calm", "peaceful", "tranquil", "placid"], definition: "(adj.) Calm, peaceful, and untroubled" },
  { word: "skeptical", synonyms: ["doubtful", "dubious", "questioning", "unconvinced"], definition: "(adj.) Not easily convinced; having doubts" },
  { word: "sluggish", synonyms: ["lethargic", "slow", "languid", "torpid"], definition: "(adj.) Slow-moving or inactive" },
  { word: "solemn", synonyms: ["serious", "grave", "earnest", "sober"], definition: "(adj.) Formal and dignified; not cheerful or smiling" },
  { word: "sophisticated", synonyms: ["refined", "cultured", "worldly", "polished"], definition: "(adj.) Having a refined knowledge of the world" },
  { word: "sporadic", synonyms: ["occasional", "irregular", "intermittent", "scattered"], definition: "(adj.) Occurring at irregular intervals; not continuous" },
  { word: "squander", synonyms: ["waste", "fritter away", "misuse", "dissipate"], definition: "(v.) To waste in a reckless or foolish manner" },
  { word: "stagnant", synonyms: ["inactive", "sluggish", "motionless", "static"], definition: "(adj.) Having no motion; showing no activity" },
  { word: "steadfast", synonyms: ["unwavering", "resolute", "firm", "committed"], definition: "(adj.) Resolutely or dutifully firm and unwavering" },
  { word: "stoic", synonyms: ["impassive", "unemotional", "detached", "unflappable"], definition: "(adj.) Enduring pain or hardship without complaint" },
  { word: "submissive", synonyms: ["obedient", "compliant", "docile", "meek"], definition: "(adj.) Ready to conform to authority; obedient" },
  { word: "subtle", synonyms: ["delicate", "nuanced", "understated", "faint"], definition: "(adj.) So delicate or precise as to be difficult to analyze" },
  { word: "superfluous", synonyms: ["unnecessary", "redundant", "excess", "surplus"], definition: "(adj.) Unnecessary, especially through being more than enough" },
  { word: "tenacious", synonyms: ["persistent", "determined", "stubborn", "dogged"], definition: "(adj.) Tending to keep a firm hold; persistent" },
  { word: "tentative", synonyms: ["uncertain", "hesitant", "provisional", "cautious"], definition: "(adj.) Not certain or fixed; done without confidence" },
  { word: "thrive", synonyms: ["flourish", "prosper", "succeed", "bloom"], definition: "(v.) To grow or develop vigorously; to prosper" },
  { word: "timid", synonyms: ["shy", "bashful", "fearful", "meek"], definition: "(adj.) Showing a lack of courage or confidence; easily frightened" },
  { word: "tranquil", synonyms: ["calm", "peaceful", "serene", "placid"], definition: "(adj.) Free from disturbance; calm" },
  { word: "transparent", synonyms: ["clear", "obvious", "evident", "plain"], definition: "(adj.) Easy to perceive or detect; not deceptive" },
  { word: "treacherous", synonyms: ["disloyal", "traitorous", "deceitful", "perfidious"], definition: "(adj.) Guilty of betrayal; not to be trusted" },
  { word: "turbulent", synonyms: ["chaotic", "tempestuous", "stormy", "volatile"], definition: "(adj.) Moving unsteadily; characterized by conflict" },
  { word: "ubiquitous", synonyms: ["omnipresent", "universal", "pervasive", "widespread"], definition: "(adj.) Present, appearing, or found everywhere" },
  { word: "unruly", synonyms: ["disorderly", "wild", "uncontrollable", "rowdy"], definition: "(adj.) Disorderly and disruptive; difficult to control" },
  { word: "vacillate", synonyms: ["waver", "fluctuate", "hesitate", "dither"], definition: "(v.) To waver between different opinions or actions" },
  { word: "vehement", synonyms: ["passionate", "fervent", "intense", "forceful"], definition: "(adj.) Showing strong feeling; forceful or passionate" },
  { word: "verbose", synonyms: ["wordy", "long-winded", "garrulous", "prolix"], definition: "(adj.) Using or expressed in more words than are needed" },
  { word: "vigilant", synonyms: ["watchful", "alert", "attentive", "wary"], definition: "(adj.) Keeping careful watch for possible danger or difficulties" },
  { word: "vindictive", synonyms: ["vengeful", "spiteful", "retaliatory", "malicious"], definition: "(adj.) Having or showing a strong desire for revenge" },
  { word: "volatile", synonyms: ["unstable", "erratic", "unpredictable", "explosive"], definition: "(adj.) Liable to change rapidly and unpredictably" },
  { word: "wary", synonyms: ["cautious", "guarded", "vigilant", "circumspect"], definition: "(adj.) Feeling or showing caution about possible dangers" },
  { word: "zealous", synonyms: ["fervent", "ardent", "passionate", "enthusiastic"], definition: "(adj.) Having or showing zeal; enthusiastically devoted" },
];

export function getRandomWords(count: number, exclude?: string[]): Word[] {
  const available = exclude
    ? WORDS.filter((w) => !exclude.includes(w.word))
    : [...WORDS];
  const shuffled = available.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function buildQuizQuestion(word: Word): {
  word: Word;
  correct: string;
  options: string[];
} {
  const correctSynonym = word.synonyms[Math.floor(Math.random() * word.synonyms.length)];

  // Pick 3 wrong options from other words' synonyms
  const otherWords = WORDS.filter((w) => w.word !== word.word);
  const shuffledOthers = otherWords.sort(() => Math.random() - 0.5);
  const wrong: string[] = [];
  for (const other of shuffledOthers) {
    const candidate = other.synonyms[Math.floor(Math.random() * other.synonyms.length)];
    if (!word.synonyms.includes(candidate) && !wrong.includes(candidate)) {
      wrong.push(candidate);
    }
    if (wrong.length === 3) break;
  }

  const options = [correctSynonym, ...wrong].sort(() => Math.random() - 0.5);
  return { word, correct: correctSynonym, options };
}
